package processing.test.fude_veatpro_android;

/* autogenerated by Processing revision 1293 on 2024-10-11 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import android.view.MotionEvent;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class fude_veatpro_android extends PApplet {



String scene = "title";
boolean isTouched = false;
boolean isdrugged = false;
float touchX, touchY;
int scene_ready = 0;
float write_deg = 0;
float p_write_deg = 0;
float easing = 0.2f;

//追加分
float pressure = 0;
boolean stopped = false;
int stopTime = 0;
int stopTimeThreshold = 500;
float stopThreshold = 0.16f;
float moveThreshold = 2;
int pmillis = 0;
int lastTouchTime = 0;

public void setup()
{ 
  //色定義
  colorMode(HSB,360,100,100,100);
  int red = color(0,100,100,30);
  int trans = color(0,100,100,0);
  
  //ボタン定義
  tb_start = new Button(trans,1350,150,400,200);
  tb_gallery = new Button(trans,1350,450,400,200);
  tb_end = new Button(trans,1350,750,400,200);
  pb_fude = new Button(red,1460,800,200,100);
  pb_reset = new Button(red,1680,800,200,100);
  pb_end = new Button(trans,1440,940,200,90);
  pb_save = new Button(trans,1680,940,200,90);
  gb_end = new Button(red,10,10,100,50);
  
  //画像読み込み
  title_image = loadImage("title_scene.jpg");
  play_image = loadImage("play_scene.png");
  makimono_button_img = loadImage("makimono_button.png");
  fude_shape = loadImage("fude_shape.png");
  
  //フォント
  font = createFont("HOT-Kaishokk-R.otf",40);
  font_normal = createFont("KleeOne-Regular.ttf",30);
  
  /* size commented out by preprocessor */;
  //frameRate(1000);
}

public void draw()
{
  stroke(0,0,100,0);
  if(scene == "title")
    title();
  else if(scene == "play")
  {
    if(scene_ready == 0)
    {
      background(0,0,100,100);
      scene_ready = 1;
    }
    play();
  }
  else if(scene == "gallery")
    gallery();
}

public void touchStarted()
{
  isTouched = true;
   if(scene == "title")//タイトル画面の時
   {
     if(tb_start.push(mouseX,mouseY))
       display_change("play");
     if(tb_gallery.push(mouseX,mouseY))
       display_change("gallery");
     if(tb_end.push(mouseX,mouseY))
       exit();
   }
   else if(scene == "play")//習字画面の時
   {
     if(pb_end.push(mouseX,mouseY))
     {
       display_change("title");
       scene_ready = 0;
     }
     if(pb_reset.push(mouseX,mouseY))
     {
       scene_ready = 0;
     }
     if(pb_save.push(mouseX,mouseY))
     {
       println("save");
       save("test.png");
     }
   }
   else if(scene == "gallery")
   {
     if(gb_end.push(mouseX,mouseY))
       display_change("title");
   }
}

public void touchMoved()
{
  isdrugged = true;
}


public void touchEnded()
{
  isdrugged = false;
  isTouched = false;
  stopped = false;
  stopTime = 0;
}
Button tb_start;
Button tb_gallery;
Button tb_end;

Button pb_end;
Button pb_save;
Button pb_fude;
Button pb_reset;

Button gb_end;

class Button{
  int bcolor;
  int x;
  int y;
  int bwidth;
  int bheight;
  
  Button(int tbcolor,int tx,int ty,int tbwidth,int tbheight){
    bcolor = tbcolor;
    x = tx;
    y = ty;
    bwidth = tbwidth;
    bheight = tbheight;
  }
  
  public void set(){
    fill(bcolor);
    rect(x,y,bwidth,bheight);
  }
  
  public boolean push(float px,float py){
    if(x <= px && px <= (x+bwidth)){
      if(y <= py && py <= (y+bheight))
        return true;
      else
        return false;
    }
    else
      return false;
  }
}
public void display_change(String str)
{
  delay(1000);
  scene = str;
}
PImage title_image;
PImage play_image;
PImage makimono_button_img;
PImage fude_shape;

PFont font;
PFont font_normal;
public void gallery()
{
  background(255);
  gb_end.set();
  textSize(20);
  fill(0);
  text("未実装",100,100);
}
public void play()
{
  //scene_ready = 0;
  image(play_image,0,0,1920,1200);
  pb_fude.set();
  pb_reset.set();
  pb_end.set();
  pb_save.set();
  image(makimono_button_img,1420,920,240,130);
  image(makimono_button_img,1660,920,240,130);
  textSize(20); 
  fill(0);
  textFont(font);
  text("終わる",1480,990);
  text("保存",1720,990);
  
  // 一定時間タッチがない場合にリセット処理
  if (millis() - lastTouchTime > stopTimeThreshold) {
    stopped = false;
  }
  
  float dx = mouseX-pmouseX;
  float dy = mouseY-pmouseY;
  int direction;

  float at_rad = atan(dy/dx);
  float at_deg = degrees(at_rad);
  float t_write_deg = 0;
  
    //象限判定
  if(dx >= 0)
  {if(dy >= 0)
      direction = 4;
    else
      direction = 1;
  }else{
    if(dy >= 0)
      direction = 3;
    else
      direction = 2;
  }
  
  //停止判定
  if(-8 <= dx && dx <= 8)
    if(-8 <= dy && dy <= 8)
      direction = 5;
  
  
  switch(direction){
    case 1:
      //println("右上");
      t_write_deg = -at_deg;
      break;
    case 2:
      //println("左上");
      t_write_deg = 180-at_deg;
      break;
    case 3:
      //println("左下");
      t_write_deg = 180-at_deg;
      break;
    case 4:
      //println("右下");
      t_write_deg = 360-at_deg;
      break;
    case 5:
      //println("停止");
      t_write_deg = p_write_deg;
      break;
    default:
      println("-------error-------");
      break;
  }
  
  //角度イージング処理
  if(180 > write_deg){
    if(t_write_deg > write_deg+180){
      t_write_deg = -(360 - t_write_deg);
    }
  }else{
    if(write_deg-180 > t_write_deg){
      write_deg = -(360 - write_deg);
    }
  }
  
  //イージングで少しずつ角度変化
  write_deg += (t_write_deg - write_deg) * easing;
  
  //write_degを0～360内に修正
  while(!(360 > write_deg && write_deg > 0))
  {
    if(write_deg > 360)
      write_deg -= 360;
    if(0 > write_deg)
      write_deg += 360;
  }
  
  float fude_deg = write_deg + 90;
  float fude_rad = radians(fude_deg);
  
  if(isTouched){
    
    float weight = 0;
    
    if(isdrugged){
      if (!stopped) { //動いている時
        weight = pow(pressure, 2) * 2000;
        stroke(0);
        strokeWeight(weight);
        //line(pmouseX,pmouseY,mouseX,mouseY);
      }
      
    pushMatrix();
    translate(mouseX,mouseY);
    rotate(-fude_rad);
    image(fude_shape,-(weight/2),-(weight/0.8f),weight,(weight/0.6f));
    popMatrix();
      
      if (pressure >= stopThreshold && dist(pmouseX, pmouseY, mouseX, mouseY) < moveThreshold) {
        stopTime += millis() - pmillis;
      } else {
        stopTime = 0;
      }
      
      if (stopTime > stopTimeThreshold && !stopped) {
        float squareSize = pow(pressure, 2) * 2000;
        noStroke();
        fill(0); 
        rect(mouseX - squareSize / 2, mouseY - squareSize / 2, squareSize, squareSize, squareSize / 4); 
        stopped = true;  
        stroke(0);
      }
      
      pmillis = millis();
      lastTouchTime = millis();
  }
  p_write_deg = write_deg;
  }
}
public void title()
{
  image(title_image,0,0,1920,1200);
  image(makimono_button_img,1300,150);
  image(makimono_button_img,1300,450);
  image(makimono_button_img,1300,750);
  tb_start.set();
  tb_gallery.set();
  tb_end.set();
  textSize(25);
  fill(0);
  textFont(font);
  text("始める",1420,300);
  text("作品一覧",1420,600);
  text("終わる",1420,900);
}
// この関数で全てのタッチイベントを手動で管理
public boolean surfaceTouchEvent(MotionEvent event){
  pressure = event.getPressure();

  int action = event.getAction();
  switch (action) {
    case MotionEvent.ACTION_DOWN:
      stopped = false;  // タッチ開始時にフラグをリセット
      stopTime = 0;
      pmillis = millis();
      break;

    case MotionEvent.ACTION_MOVE:
      touchMoved();  // タッチ移動時に描画処理を行う
      break;

    case MotionEvent.ACTION_UP:
      touchEnded();  // タッチ終了時に再び描画を可能に
      break;
  }

  return super.surfaceTouchEvent(event); 
  
}


  public void settings() { fullScreen(); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "fude_veatpro_android" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
